add filter per year for financial overview statistics
teamforus/forus-backend pull request #2334
Opened 2024-09-29 23:19 UTC by aghimpu

## Changes description

## Developers checklist
- [ ] **Autotests are passed locally**
- [ ] **Migration rollback works** - if there is migration, check rollback
- [ ] **Autotests are added**:
   - bugfix - unit/feature test for this scenario if possible
   - new small/medium feature - simple feature test for positive scenarios

## QA checklist
- [ ] **Translations are done**
- [ ] **Endpoint is fast on dump** - if there is new endpoint or changed query, endpoints that are using changed query - working fast on production dump, <2s

2024-10-24 09:36 UTC, irinaBerendeeva87 requested changes
### Checked:
**Financial overview**

❌ data in exported CSV file is displayed in units/tens instead of thousands
<img width="1310" alt="Screenshot 2024-10-24 at 09 49 18" src="https://github.com/user-attachments/assets/177ecc83-9e94-488e-8fa0-b992aef68ecb">

❌ download whole numbers instead of fractions
<img width="1297" alt="Screenshot 2024-10-24 at 09 54 01" src="https://github.com/user-attachments/assets/c48c400a-8e25-44db-91dc-6a8e96e47bea">
❌ current year data is downloaded instead of 2023 data

https://github.com/user-attachments/assets/8dc40ef3-37c9-4b05-aa6f-31ee9d9429dd

**Tegoeden**
❌ no errors in the console
500 error after chose a format and click "Submit button" in  "Selecteer export type" modal. 
 
https://github.com/user-attachments/assets/3242c2f7-d0de-48f4-bb4e-e2a78f1da917
❌ incorrect data on the table
 
<img width="829" alt="Screenshot 2024-10-24 at 11 23 58" src="https://github.com/user-attachments/assets/1e9458c0-cb36-46cb-a823-b54ba1badf7e">

based on data in data base nijmegen has 5 vouchers in Meedoenregeling 

<img width="849" alt="Screenshot 2024-10-24 at 11 21 51" src="https://github.com/user-attachments/assets/134f68cd-821c-4f2b-ad4e-07699bcbf7e5">

✅ checked in different implementations

--------------------------
 My proposal:
 **Not related to this PR**
 Add the year to the description of the downloaded  file to make it more informative 
 - Now it looks like this 
 sponsor_Gemeente Nijmegen_2024-10-24 10_06_17
 
 ❌ in the downloaded file in total row columns  "Uitgaven" and  "Huidig saldo" are misplaced
<img width="483" alt="Screenshot 2024-10-24 at 10 20 07" src="https://github.com/user-attachments/assets/d59526a8-61c7-4713-9d69-1e7458dc1a72">

2024-10-31 10:43 UTC, irinaBerendeeva87 requested changes
### Checked:
❌  adding code related Carbon lead to 500 error while loading Funds page 

<img width="646" alt="Screenshot 2024-10-31 at 11 06 57" src="https://github.com/user-attachments/assets/1833debb-15af-4c6a-bba9-f543774c1ff6">

 <details>  <summary>backend laravel log</summary>  [2024-10-31 11:04:43] local.ERROR: Not enough data available to satisfy format {"userId":"0xf0f8d839ef4449af2c9078a204efbd6be361112b","exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Not enough data available to satisfy format at /var/www/forus-backend/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:624)
* [stacktrace]
* #0 /var/www/forus-backend/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(660): Carbon\\Carbon::rawCreateFromFormat()
* #1 /var/www/forus-backend/app/Statistics/Funds/FinancialOverviewStatistic.php(131): Carbon\\Carbon::createFromFormat()
* #2 /var/www/forus-backend/app/Http/Resources/FundResource.php(73): App\\Statistics\\Funds\\FinancialOverviewStatistic::getFinancialData()
* #3 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(65): App\\Http\\Resources\\FundResource->toArray()
* #4 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
* #5 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
* #6 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map()
* #7 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(64): Illuminate\\Support\\Collection->map()
* #8 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(102): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
* #9 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(108): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray()
* #10 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
* #11 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(134): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
* #12 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(114): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
* #13 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(902): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
* #14 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(887): Illuminate\\Routing\\Router::toResponse()
* #15 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Routing\\Router->prepareResponse()
* #16 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
* #17 /var/www/forus-backend/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #18 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware->handle()
* #19 /var/www/forus-backend/app/Http/Middleware/ClientVersionMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #20 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientVersionMiddleware->handle()
* #21 /var/www/forus-backend/app/Http/Middleware/ClientTypeMiddleware.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #22 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientTypeMiddleware->handle()
* #23 /var/www/forus-backend/app/Http/Middleware/ImplementationKeyMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #24 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ImplementationKeyMiddleware->handle()
* #25 /var/www/forus-backend/app/Http/Middleware/DomainMiddleware.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #26 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\DomainMiddleware->handle()
* #27 /var/www/forus-backend/app/Http/Middleware/LocaleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #28 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\LocaleMiddleware->handle()
* #29 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #30 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
* #31 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #32 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
* #33 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
* #34 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
* #35 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
* #36 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
* #37 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
* #38 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #39 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
* #40 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #41 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
* #42 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #43 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
* #44 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
* #45 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
* #46 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
* #47 /var/www/forus-backend/v [...]

2024-11-05 13:35 UTC, irinaBerendeeva87 requested changes
### Checked:
not fixed:
- adding code related Carbon lead to 500 error while loading Funds page
<img width="646" alt="Screenshot 2024-10-31 at 11 06 57" src="https://github.com/user-attachments/assets/1833debb-15af-4c6a-bba9-f543774c1ff6">

<details>  <summary>backend laravel log</summary> 
[2024-11-05 14:33:27] local.ERROR: Not enough data available to satisfy format {"userId":"0xf0f8d839ef4449af2c9078a204efbd6be361112b","exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Not enough data available to satisfy format at /var/www/forus-backend/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:624)
[stacktrace]
#0 /var/www/forus-backend/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(660): Carbon\\Carbon::rawCreateFromFormat()
#1 /var/www/forus-backend/app/Statistics/Funds/FinancialOverviewStatistic.php(132): Carbon\\Carbon::createFromFormat()
#2 /var/www/forus-backend/app/Http/Resources/FundResource.php(73): App\\Statistics\\Funds\\FinancialOverviewStatistic::getFinancialData()
#3 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(65): App\\Http\\Resources\\FundResource->toArray()
#4 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#5 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
#6 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map()
#7 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(64): Illuminate\\Support\\Collection->map()
#8 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(102): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#9 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(108): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray()
#10 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
#11 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(134): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
#12 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(114): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
#13 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(902): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
#14 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(887): Illuminate\\Routing\\Router::toResponse()
#15 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Routing\\Router->prepareResponse()
#16 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/forus-backend/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware->handle()
#19 /var/www/forus-backend/app/Http/Middleware/ClientVersionMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientVersionMiddleware->handle()
#21 /var/www/forus-backend/app/Http/Middleware/ClientTypeMiddleware.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ClientTypeMiddleware->handle()
#23 /var/www/forus-backend/app/Http/Middleware/ImplementationKeyMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ImplementationKeyMiddleware->handle()
#25 /var/www/forus-backend/app/Http/Middleware/DomainMiddleware.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\DomainMiddleware->handle()
#27 /var/www/forus-backend/app/Http/Middleware/LocaleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\LocaleMiddleware->handle()
#29 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#31 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#33 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#35 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#36 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#37 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#40 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#42 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#45 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21) [...]

2024-11-05 15:39 UTC, aghimpu commented
> ### Checked:
> * adding code related Carbon lead to 500 error while loading Funds page

> - export statistics without errors export statistic for 2024 year for Groningen lead to 500 error

Done (both)

2024-11-06 12:00 UTC, irinaBerendeeva87 approved these changes
### Checked:
✅ Fixed:
-500 error  while loading Funds page
- 500 error while export statistics for 2024 year for Groningen
✅ no errors in the console
✅ checked in different implementations

2024-11-06 12:04 UTC, merged